- name: playbook server
  hosts: web
  become: yes
  tasks:
  - name: install nginx
    ansible.builtin.packages:
     name: nginx
     state: present
  - name: run nginx
    ansible.builtin.service:
     name: nginx
     state: started