- name: play1
  hosts: web
  tasks:
   - name: playbookandtask-1
     ansible.builtin.debug:
     msg: "hello from p-1 task-1"

- name: play2
  hosts: web
  tasks:
    - name: playbookandtask-2
      ansible.builtin.debug:
       msg: "hello from p-2 task-2"