- name: playbook-variables
  hosts: localhost
  vars_files:
  - variables.yaml
  tasks:
  - name: check variables
    vars:
      Course: "devops with aws"
    ansible.builtin.debug:
       msg: "hi! i am {{Course}}, {{Trainer}},duration is {{Duration}} 