- name: loops in ansible
  hosts: localhost
  tasks:
  - name: print person
    ansible.builtin.debug:
     msg: "hello {{item}}"
    loop:
    - ramesh
    - suresh
    - himesh
    - naresh
    - harish