- name: variables-prompt
  hosts: localhost
  vars_prompt:
   - name: username
     prompt: enter your username
     private: false
   - name: password
     prompt: enter your password
     private: true
  tasks:
  - name: print with prompt
    ansible.builtin.debug:
     msg: "username is {{username}}, password is {{password}}"