- name: playbook-variables
  hosts: localhost
  vars:
    Course: "devops"
    Trainer: "sivakumar"
    Duration: "30mins"
  tasks:
  - name: check variables
    vars:
      Course: "devops with aws"
    ansible.builtin.debug:
       msg: "hi! i am {{Course}}, {{Trainer}},duration is {{Duration}} "