- name: playbook-variables
  hosts: web
  vars:
    Course: "devops"
    Trainer: "siva"
    Duration: "30mins"
   tasks:
   - name: check variables
     ansible.builtin.debug:
      msg: "hi! i am {{Course}}, {{Trainer}},duration is {{Duration}} "